name: jupyter notebooks test
#eventually it should do more but let's start here
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: fano_5_2024
        environment-file: environment.yml
        auto-activate-base: false
    - name: Finish conda setup
      run: |
        conda install nbmake pytest -n fano_5_2024
        conda run python -m ipykernel install --user --name fano_5_2024
        conda run -n fano_5_2024 pytest --nbmake --nbmake-kernel=fano_5_2024 0-
