name: jupyter notebooks test
#eventually it should do more but let's start here
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: fano_5_2024
        environment-file: environment.yml
    - run: |
        conda install nbmake -n fano_5_2024
        conda env list
        pytest --nbmake --nbmake-kernel=fano_5_2024 0-
