name: jupyter notebooks test
#eventually it should do more but let's start here
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: fano_5_2024
        environment-file: environment.yml
        auto-activate-base: false
    - name: Finish python setup
      run: |
        conda install nbmake pytest -n fano_5_2024
        conda env list
        conda info
        conda run -n fano_5_2024 python -m ipykernel install --user --name fano_5_2024
    - name: Test python notebooks
      run: |
        conda run -n fano_5_2024 pytest --nbmake --nbmake-kernel=fano_5_2024 --nbmake-timeout=7700 ?-*/*.ipynb
        conda run -n fano_5_2024 pytest --nbmake --nbmake-kernel=fano_5_2024 --nbmake-timeout=2000 SCDMS_flux/*.ipynb
